# Generated by Django 4.2.5 on 2023-09-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('number', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
